### ISSUE TITLE
Práctica 1

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-team-noble#2]
[Practica 1.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-team-noble/files/8105405/Practica.1.pdf)

**Comment by Yabin-2021** [comment]
Calificación **20 %**

**Comment by josealfredo79** [comment]
Bien hecho y revisado
